### ISSUE TITLE
Using table name and column name alias while using imporJson method in sqlite-porter plugin ?

### ISSUE THREAD

**Issue by Priya-Ahuja** [dpa99c/cordova-sqlite-porter#10]
I am using Cordova-SQLite-porter plugin for sending data in the SQLite db. I am getting the data from WEB services as JSON only but the alias for table and column names are coming? Is it possible to use aliases to insert data into Db?

**Comment by dpa99c** [comment]
AFAIK the [SQLite ALIAS](https://www.tutorialspoint.com/sqlite/sqlite_alias_syntax.htm) allows you to alias table/column names within the scope of a single SQL statement using the `AS` keyword, therefore it doesn't make sense that a web services would syndicate table/column names as an alias. [See here](http://stackoverflow.com/questions/9099906/alias-for-table-name-in-sql-insert-statement)).

The only way a permanent alias can be made is to create a [view](https://sqlite.org/lang_createview.html) but in this case the view name and its column name aliases should be used as table/column names in the JSON structure as if they are a concrete table.

Hence use of aliases within this plugin does not make sense.

**Comment by Priya-Ahuja** [comment]
Thanks for the help..Anyhow I modified the plugin to achieve this functionality by adding a  function sqlEscape(value){
        var my_val = value.replace(/([A-Z])/g, "_$1").toUpperCase();
    //console.log(my_val);
         return my_val;
     }
