### ISSUE TITLE
Getting datatype mismatch error while importing from json.

### ISSUE THREAD

**Issue by bik-elumina** [dpa99c/cordova-sqlite-porter#11]
I have a table created with the following statement

CREATE TABLE IF NOT EXISTS exam_table (id integer primary key AUTOINCREMENT,  moodleexamid integer unique, examname text, examdesc text, examinstructions text, noofstations integer, examvenue text, examstartdate numeric, examstarttime numeric,  examenddate numeric, examendtime numeric, examstaffid text, isDownloaded integer, isuploaded integer, timecreated DATETIME, timemodified datetime DEFAULT CURRENT_TIMESTAMP)"

I am able to export data from the db but when I am trying to import the data I a getting the following error.(**Note** - The data contains string with html tags)

`The following error occurred: {"code":0,"message":"Failed to import SQL; message=datatype mismatch","statement":"INSERT OR REPLACE INTO exam_table SELECT 'Test Examination2' AS 'examname', '1' AS 'id', '22:40:00' AS 'examstarttime', '0' AS 'isDownloaded', '22:40:00' AS 'examendtime', '<p>Test Examination2<br></p>' AS 'examinstructions', '8-06-2016' AS 'examenddate', '8-06-2016' AS 'timecreated', 'sydney' AS 'examvenue', '2' AS 'noofstations', '0' AS 'isuploaded', '2017-01-05 11:10:49' AS 'timemodified', 'teststaff1' AS 'examstaffid', '14' AS 'moodleexamid', '<p>Test Examination2<br></p>' AS 'examdesc', '8-06-2016' AS 'examstartdate' UNION SELECT  'Test Exam - 8/6/2016', '2', '02:25:00', '0', '02:25:00', '<p>Test Exam - 8/6/2016<br></p>', '9-06-2016', '9-06-2016', 'sydney', '2', '0', '2017-01-05 11:10:49', 'teststaff1', '15', '<p>Test Exam - 8/6/2016<br></p>', '9-06-2016' UNION SELECT  'Test Exam - CE243010', '3', '19:55:00', '1', '19:55:00', '<p>Test Exam - CE243010<br></p>', '9-06-2016', '9-06-2016', 'sydney', '2', '0', '2017-01-05 11:10:49', 'teststaff1', '19', '<p>Test Exam - CE243010<br></p>', '9-06-2016' UNION SELECT  'Testing Issue 158', '4', '15:50:00', '0', '23:50:00', '<p>This exam is created to test the OSCE issue #158</p><p>sdgsdfg</p><p>sdfhdfghdfh</p><p>df dfhjgh fdghgfjh ghjghj,kfghjk dhgdkfgh dskjghkdfgh fghdfkh kdfg dfkghkdfhk fdhdfhkdfjhkj fghdfkghdkfhdkfghgfhkdfk</p><p><br></p>', '24-11-2016', '22-11-2016', 'sydney', '2', '0', '2017-01-05 11:10:49', 'teststaff1', '22', '<p>This exam is created to test the OSCE issue #158</p><p>sdgsdfg</p><p>sdfhdfghdfh</p><p>df dfhjgh fdghgfjh ghjghj,kfghjk dhgdkfgh dskjghkdfgh fghdfkh kdfg dfkghkdfhk fdhdfhkdfjhkj fghdfkghdkfhdkfghgfhkdfk</p><p><br></p>', '22-11-2016'"}

`

**Comment by dpa99c** [comment]
Please provide the JSON structure you are trying to import. 

The most likely cause is unescaped control characters in the values.

**Comment by bik-elumina** [comment]
Please find below the json file which is exported from sqlite db while importing this json datatype mismatch error is coming.

https://drive.google.com/file/d/0B0iptWwrPJNOdXgxS0p6OGl1dGs/view?usp=sharing

**Comment by dpa99c** [comment]
Looking at your table definition vs the data in the JSON structure, it looks like the data mismatch error is because you are trying to import non-numeric values into fields defined with NUMERIC datatype.

For example, you define `examenddate numeric` but then try to import `"examenddate":"8-06-2016"`. 

`-` is not a valid character for datatype NUMERIC, hence a datatype mismatch error will be raised.

You need to import dates/times either as TEXT or DATETIME but not NUMERIC.

Not an problem with the plugin though, hence closing the issue.
