### ISSUE TITLE
Unable to import all items 

### ISSUE THREAD

**Issue by FelixHerrera** [dpa99c/cordova-sqlite-porter#21]
I am using the plugin to import hundreds to thousands of items. Depending on the size of the json array I am importing using different batch sizes will yield a different number items imported. Sometimes they all import and sometimes only some items will import. Only using the 0.1.2 version of the plugin will consistently yield all items imported.

**Comment by dpa99c** [comment]
Do you mean you are missing records from the DB or just that the overall count is different?

I've just regression tested the latest version of the plugin within the [example project](https://github.com/dpa99c/cordova-sqlite-porter): the "complex" dataset includes about 15,000 records and I was able to import and export the DB multiple times with consistent results.

**Comment by FelixHerrera** [comment]
I am missing records from the DB. The samples I use vary, some are around 6000 items some are as few as 100.

**Comment by dpa99c** [comment]
I've created a [branch of the example project](https://github.com/dpa99c/cordova-sqlite-porter-example/tree/21) with a modified app which regression tests importing/exporting 15,000+ records via a JSON dump. 

It iterates 20 times and on each iteration compares the import/export count and exported data with the previous result. If any inconsistencies are found, the test will fail. I have run it 5 times and it has passed each time. Please build+run this branch (or use the pre-built APK) to confirm whether you are able to reproduce these results with the test data set.

If not, then I suggest you replace the test data set with your problematic data set within that test project and re-run the regression test to confirm whether data inconsistencies are found.

**Comment by airstep** [comment]
Also question - why new lines not imported correctly.?.. All text in one string after import...

I think it's bcz of this [line](https://github.com/dpa99c/cordova-sqlite-porter/blob/master/www/sqlitePorter.js#L73) of code

**Comment by dpa99c** [comment]
@airstep that's a different issue from the one outlined here - are you also losing data during import?

And do you mean you're losing line endings that are in the row values or between the SQL statements themselves?

**Comment by airstep** [comment]
In row values bcz in code you delete \n\r:

`var totalCount, currentCount, statements = sql.replace(/[\n\r]/g,"") // strip out line endings`

replaced to

`var totalCount, currentCount, statements = sql. //replace(/[\n\r]/g,"")  strip out line endings`

fixes this issue

**Comment by dpa99c** [comment]
Removing that statement will work fine if your source SQL is neat, but if it contains comments and line breaks between the SQL statements, it will throw off the count and causes issues. 

However, I'll tighten up the regex to remove only inter-statement line breaks which should resolve your issue.

Closing this issue though as I can find no evidence of imported data being intermittently lost.
