### ISSUE TITLE
What about SQL injection?

### ISSUE THREAD

**Issue by jgfet** [dpa99c/cordova-sqlite-porter#25]
Does this plugin properly escape stuff? Didnt' see this at a glance in the samples...

**Comment by dpa99c** [comment]
This plugin doesn't make any attempt to prevent SQL injection for the simple reason that I don't see that SQL injection is a major security problem on a client-side database. The database is only on the client device, hence if the user injects SQL to wipe or damage the database, they will only do so on their own device. If it's the security of the data in the database that's your concern, there's easy ways to access the database content on the client device with needing to use SQL injection.

Can you give me an example of why SQL injection prevention would be necessary on a client-side database in a Cordova app?

**Comment by dpa99c** [comment]
Closed due to no response from OP
