### ISSUE TITLE
Exported SQL CREATE before DELETE

### ISSUE THREAD

**Issue by Arsyad** [dpa99c/cordova-sqlite-porter#28]
I am testing exportDBToSql function and it seems in the exported SQL, the create statement is written first before DROP table. For example:

CREATE TABLE kv (key text primary key, value text);
DROP TABLE IF EXISTS kv;

Is this a bug?

**Comment by dpa99c** [comment]
Appears to be a bug introduced by PR #26.

**Comment by dpa99c** [comment]
Fix published to npm in `uk.co.workingedge.cordova.plugin.sqliteporter@1.0.2`
