### ISSUE TITLE
Importing 16mb sql file error: "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by chauthai** [dpa99c/cordova-sqlite-porter#3]
Hi, 
I'm trying to import a 16 mb sql file and I'm getting this error. Is it related to your plugin or to SQLitePlugin?

``` javascript
RangeError: Maximum call stack size exceeded
    at String.match (native)
    at null.fn (file:///android_asset/www/plugins/uk.co.workingedge.cordova.plugin.sqliteporter/www/sqlitePorter.js:75:22)
    at SQLitePluginTransaction.start (file:///android_asset/www/plugins/io.litehelpers.cordova.sqlite/www/SQLitePlugin.js:283:12)
    at file:///android_asset/www/plugins/io.litehelpers.cordova.sqlite/www/SQLitePlugin.js:144:32
```

**Comment by dpa99c** [comment]
It's [Line 75 of this plugin](https://github.com/dpa99c/cordova-sqlite-porter/blob/master/www/sqlitePorter.js#L75) that's raising the error. It's attempting to perform a regex match on the 16Mb string, and the String.match() is recursive so it's exceeding the call stack recursion limit in the WebView. 

I could extend the plugin to split the SQL statements into smaller chunks if the input exceeds a given size, but I don't have much time right now. 

As a quick workaround, you could this yourself before passing the smaller strings to the plugin or you could extend the plugin to do this yourself (and I could merge your changes via a pull request).

**Comment by chauthai** [comment]
@dpa99c apparently it's a bug in the V8 engine of the webview on Android. I've just tested it in iOS and it seems fine. (https://github.com/nodejs/node/issues/759)
The plugin still doesn't run through the whole file now and stops at statement 15109 of ca. 50000. I guess it has something to do with white spaces in a SQL statement.

**Comment by chauthai** [comment]
Ok, it seems my sql file was containing invalid chars in some strings.
I fixed them it works now.
Thanks for your time.
