### ISSUE TITLE
Stripping out comments in importSqlToDb results in invalid statements

### ISSUE THREAD

**Issue by dnn1s** [dpa99c/cordova-sqlite-porter#30]
```
var statements = sql
   .replace(/(?:\/\*(?:[\s\S]*?)\*\/)|(?:([\s;])+\/\/(?:.*)$)/gm,"") // strip out comments
   .match(statementRegEx);
```

The data that I tried to import included a value that contained two forward slashes ("foo//bar"). Applying the regular expression resulted in a statement that has been cut off within the columns value, making it fail. In my case (since I'm in full control of the SQL that my app receives and *know* that it will never include any comments), I'm able to remove the line for stripping out comments, but this might not apply to other users of this plugin.

**Comment by devnix** [comment]
Fixed in #36
