### ISSUE TITLE
RETURN FALSE ON IMPORTJSONTODB OR IMPORTSQLTODB WITH NO ERRORS

### ISSUE THREAD

**Issue by lennonfuston** [dpa99c/cordova-sqlite-porter#38]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**
functions importSqlToDb & importJsonToDb both return false with no errors on .then and .catch don't show errors..
e.g.:
let sql = 'CREATE TABLE Artist ([Id] PRIMARY KEY, [Title]);' + 'INSERT INTO Artist(Id,Title) VALUES ("1","Fred");'; // SAME AS DOCUMENTATION
this.sqlitePorter.importSqlToDb(db, sql).then((done) => {
console.log('IMPORT', JSON.stringify(done)); // "done" is 0 => "false" and after all that they don't import Tables and Rows to .db

**Expected behavior:**
Import .sql to .db

**Steps to reproduce:**
Create a new blank project ionic3 and install plugin sqlite and sqlite porter for documentation of ionic3 website e try to import .sql to .db

**Environment information**

- Cordova CLI version 
	- 8.0.0
- Cordova platform version
	- Installed platforms:
  android 7.0.0
  ios 4.5.4
Available platforms:
  browser ~5.0.1
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
- Plugins & versions installed in project (including this plugin)
    - cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"
onesignal-cordova-plugin 2.4.0 "OneSignal Push Notifications"
uk.co.workingedge.cordova.plugin.sqliteporter 1.0.4 "sqlite porter"
- Dev machine OS and version, e.g.
    - OSX
        - ProductName:	Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F77
        
_Runtime issue_
- Device details
    - _e.g. iPhone X Simulator
- OS details
    - _e.g.Android 7.0.1
	
_Android build issue:_	
- Node JS version
    - v10.1.0
- Gradle version
	- 4.1			4.6			buildOutputCleanup
- Target Android SDK version
	- 26
	
- XCode version
9.4.1

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 7.0.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v10.1.0
    npm               : 5.6.0
    OS                : macOS High Sierra
    Xcode             : Xcode 9.4.1 Build version 9F2000

Environment Variables:

    ANDROID_HOME : /Users/user/Library/Android/sdk

Misc:

    backend : pro

- Installed Ionic Native modules and versions
├── @ionic-native/core@4.7.0
├── @ionic-native/device@4.7.0
├── @ionic-native/file@4.7.0
├── @ionic-native/in-app-browser@4.7.0
├── @ionic-native/in-app-purchase@4.9.0
├── @ionic-native/onesignal@4.9.0
├── @ionic-native/splash-screen@4.7.0
├── @ionic-native/sqlite@4.9.0
├── @ionic-native/sqlite-porter@4.9.0
├── @ionic-native/status-bar@4.7.0

**Related code:**

    this.sqlite.create({
      name: 'mydb.db',
      location: 'default'
    }).then((db: SQLiteObject) => {
      console.log('CHECK DB', JSON.stringify(db));
      let sql = 'CREATE TABLE Artist ([Id] PRIMARY KEY, [Title]);' + 'INSERT INTO Artist(Id,Title) VALUES ("1","Fred");';
      this.sqlitePorter.importSqlToDb(db, sql).then((done) => {
        console.log('IMPORT', JSON.stringify(done));
        db.executeSql("SELECT * FROM Artist;", {}).then((data) => {
          console.log(JSON.stringify(data.rows));
          let grupos = [];
          for (var i = 0; i < data.rows.length; i++) {
            grupos.push(data.rows.item(i));
          }
          console.log('grupos', JSON.stringify(grupos));
          this.sqlitePorter.exportDbToJson(db).then((data) => {
            console.log('EXPORT', JSON.stringify(data));
          });
        }).catch((e) => {console.error('SELECT ERROR', JSON.stringify(e));});
      });
    }).catch((e) => {console.error('CHECK DB ERROR', JSON.stringify(e));});

**Console output**
IMPORT 0

**Other information:**

# Feature request

# Documentation issue

**Comment by dpa99c** [comment]
Looks like another bug introduced by PR #36 😞 
While it improves the stripping of SQL comments, it also [removed the splitting of the SQL string into separate statements](https://github.com/dpa99c/cordova-sqlite-porter/pull/36/files#diff-2275597cab287a4606bfce80178b3680L77) meaning no statements are ever imported.
Will publish a patch release to fix.

**Comment by dpa99c** [comment]
Fix published to npm in v1.0.5
