### ISSUE TITLE
Plugin doesn't work on iOS using Ionic DevApp

### ISSUE THREAD

**Issue by rodrake1** [dpa99c/cordova-sqlite-porter#42]
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

Started a Ionic3 blank project and installed plugins and npm packages for sqlite and sqlite-porter. Database was created successfully using sqlite, but when trying to fill the database using sqlite-porter to import a sql file, it throws the error "plugin_not_installed".

**Expected behavior:**

Data should be imported to the database after the sql statements being executed with `importSqlToDb`.

**Steps to reproduce:**

1) Installed Ionic 3.20
2) Started blank project
3) Installed sqlite and sqlite-porter plugins using:
```
$ ionic cordova plugin add cordova-sqlite-storage
$ npm install --save @ionic-native/sqlite
$ ionic cordova plugin add uk.co.workingedge.cordova.plugin.sqliteporter
$ npm install --save @ionic-native/sqlite-porter
```
4) Implemented the code as seen in https://github.com/rodrake1/sqlite-app
5) Ran it on iPhone 7 using Ionic DevApp latest version
6) Created database using first button
7) Tried to fill database using second button

**Environment information**

- Cordova CLI version : 7.0.1

- Cordova platform version: 
  android ~6.2.2
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  webos ~3.7.0
  windows ~5.0.0

- Plugins & versions installed in project (including this plugin)
cordova-sqlite-storage 2.5.2 "Cordova sqlite storage plugin"
uk.co.workingedge.cordova.plugin.sqliteporter 1.1.0 "sqlite porter"

- Dev machine OS and version, e.g.
    - Windows 7
        
_Runtime issue_
- Device details
    - iPhone 7

- OS details
    -  iOS 12.1
	
- Node JS version: 8.12.0

**Related code:**

```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**

<details>
<summary>plugin_not_installed</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

# Feature request

# Documentation issue

**Comment by dpa99c** [comment]
Ionic DevApp only supports a [selective set of native plugins](https://ionicframework.com/docs/appflow/devapp/#native-cordova-plugin-support) of which this plugin is not one of them.
If you wish to use this plugin, you need to do a full native build of the iOS app using Ionic/Cordova.

**Comment by rsalt** [comment]
Hi I am facing the same issue, where as i am couldn't able to import .sql schema in my sqlite db using sqlite porter plugin in ionic 3 project.
![image](https://user-images.githubusercontent.com/13706104/57759447-94729080-7717-11e9-8dc7-8ca2de24219e.png)

**Comment by rsalt** [comment]
@dpa99c do you have any of example or reference can follow to do so.!!!

**Comment by dpa99c** [comment]
https://github.com/dpa99c/cordova-sqlite-porter-example
