### ISSUE TITLE
Export in JSON but using the sql query

### ISSUE THREAD

**Issue by ghost** [dpa99c/cordova-sqlite-porter#52]
I want to export my data as JSON format. But I want also add a (**select**) query with some (**where**) condition to select some specific data. So, Is it possible to export data which are matched with the where conditions only??

**Comment by dpa99c** [comment]
This tool is intended to be a database dumper, so specific filters for data are not intended.
If you want to filter the data, you should post-process the JSON.

**Comment by ghost** [comment]
Problem is its a large database. So, if I cant select specific data then the file size will be an issue to transfer the output data...
