### ISSUE TITLE
This plugin has a maintained repo now - please use and follow

### ISSUE THREAD

**Issue by EYALIN** [dpa99c/cordova-sqlite-porter#59]
this plugin creator @dpa99c , did fantastic work, and we highly appreciate him
for now this plugin is not maintained anymore (not responding for a while).
we moved to a maintained plugin (which forked from this one) to here:
https://github.com/EYALIN/community-cordova-plugin-sqlite-porter

you can install it as an npm package:
cordova plugin add community-cordova-plugin-sqlite-porter

**Comment by dpa99c** [comment]
This plugin is not unmaintained - it's still actively used in multiple production apps.
It is, however, mostly stable and feature-complete so hasn't been updated in a while.
PRs for bug fixes/additional features will still be accepted.
